### ISSUE TITLE
Compile to smali error on every file.

### ISSUE THREAD

**Issue by ghost** [ollide/intellij-java2smali#7]
Hello, I'm getting compile error on every file I try it builds but the Compile to smali wont work so I know it's not my code.

error:

> Information:2/24/2017 9:28 PM - Compilation completed with 1 error and 0 warnings in 1s 289ms
 Error:0

Event log:

> 9:26:58 PM Gradle sync started
9:27:43 PM Gradle sync completed
9:27:47 PM Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies]
9:27:55 PM Gradle build finished in 11s 343ms
9:28:59 PM Compilation completed with 1 error and 0 warnings in 1s 289ms

**Comment by ollide** [comment]
Hi @Rab3020,

which version of Android Studio and the Java2Smali plugin are you using?
Could you please also provide a more detailed build log or a small sample project reproducing this error?

Thanks! 🙂

**Comment by ollide** [comment]
Closed as this is probably a project compilation error and no further details were given.

**Comment by z3ntu** [comment]
I currently have the same issue. It worked 5 minutes ago with everything the same version and now it doesn't work anymore with the `Error: 0`.
Plugin version is 1.6 and Android studio version is 2.3.3 on Linux. I tried restarting the IDE, cleaning the project and reducing the Java class to a minimum (Java main method with one integer assignment) and I still get that error.

**Comment by z3ntu** [comment]
I restarted a bunch more times and now it works again. :man_shrugging: Do you have any idea where that `Error: 0` message comes from? The string "Error" isn't included in your plugin so it has to be from some other source...

**Comment by ollide** [comment]
Hi Luca,

could you please attach a copy of your _minimum project_?

**Comment by z3ntu** [comment]
It was the file 

```
package vm.manager;

/**
 * Created by luca on 27.07.17.
 */

public class Test {
    public static void main(String[] args) {
        int test = 1;
    }
}
```

but I'm pretty sure it's not the file but some other mystical error in the background... I've put the file into an Android project but I don't think that matters too much either...

**Comment by BCsl** [comment]
Also not work on Android Studio 3.0

`Error:Android Gradle Build Target: java.util.ServiceConfigurationError: com.android.ide.common.blame.parser.PatternAwareOutputParser: Provider com.squareup.sqldelight.intellij.parsing.OutputParser could not be instantiated`

**Comment by ollide** [comment]
Hi @BCsl ,

could you please raise another issue for your comment? The AS 3.0 problem seems to be more evident and I'd like to handle this separately.

Thanks!

**Comment by ollide** [comment]
I've just released a new version of the plugin (2.0.1) which delegates the build job better than before and therefore should fix these kind of errors. As this issue is more than three years old, I'll close this now. Please raise a new one, if you encounter any issues with the current version.
